### ISSUE TITLE
Dependencies on the environment variables are not properly reported to cargo

### ISSUE THREAD

**Issue by nagisa** [rust-lang/pkg-config-rs#104]
Changing `PKG_CONFIG_PATH` and rebuilding some crate that depends on the `pkg_config` crate (directly or indirectly) will not rebuild the crates that pull their dependencies from `pkg-config`.

**Comment by sdroege** [comment]
Indeed! Do you want to provide a PR for that?

**Comment by nagisa** [comment]
Hm, looks like the behavior is governed by the [`env_metadata`](https://docs.rs/pkg-config/0.3.17/pkg_config/struct.Config.html#method.env_metadata) builder option, which defaults to `false`.

I suspect its just an incorrect default, as most of the ecosystem will want it set to `true` but very rarely people will hit problems in developing when this is not set, leading to pretty much entire ecosystem misusing this library.

@sdroege do you think us changing the default from `false` to `true` be a change that we can afford to make? It _shouldn't_ break any code per se...

**Comment by nagisa** [comment]
@sdroege I would appreciate a release with this included. It is not super time sensitive, but I suspect that might take many months for a next release if we wait to collect more changes before a release.

**Comment by sdroege** [comment]
Yeah, I was going to do one later today. It's easy enough
