### ISSUE TITLE
Improving cross-compilation experience

### ISSUE THREAD

**Issue by kornelski** [rust-lang/pkg-config-rs#109]
Currently pkg-config-rs tries to prevent incorrect use of pkg-config for cross-compilation:

> Cross compilation detected. Use PKG_CONFIG_ALLOW_CROSS=1 to override

However, judging by questions on the Rust forum, users don't understand the problem. They only set the variable as instructed, and are disappointed that it still doesn't work.

I suggest changing this message to point users to a more complete explanation, e.g:

> pkg-config must be configured for cross-compilation. See https://github.com/rust-lang/pkg-config-rs#how-to-cross-compile

which would then instruct users to set sysroot, etc. first before enabling `PKG_CONFIG_ALLOW_CROSS=1`.

**Comment by ryankurte** [comment]
I was about to open an issue requesting the ability to set this via configuration, so we don't need to surprise users with environmental variables when building crates.
I am however unclear on why this couldn't be done automatically if we detect the target to be different to the host?

Somewhat related issue about building `*-sys` crates: [rust-embedded#481](https://github.com/rust-embedded/wg/issues/481)

**Comment by sdroege** [comment]
> I was about to open an issue requesting the ability to set this via configuration

What configuration are you thinking of, ooc? Apart from environment variables there is nothing really or is there?

I agree that this should be documented better though. Someone wants to give it a try?

**Comment by kornelski** [comment]
> I am however unclear on why this couldn't be done automatically

You mean setting "PKG_CONFIG_ALLOW_CROSS=1"? It's a totally artificial barrier added intentionally. It could be removed, but it would only lead to worse errors at later stages of the build.

The problem is that `pkg-config` doesn't support cross-compilation, unless user puts work to trick pkg-config into doing the right thing for compilation.

`PKG_CONFIG_ALLOW_CROSS=1` is like a "ROAD CLOSED" sign. Yes, you can very easily remove the "ROAD CLOSED" sign! But it doesn't achieve anything, and only makes things worse.

The real instruction should be:

1. Install libraries for the target system
2. Configure pkg-config to use target system's sysroot
3. Then try building again

Point (1) is a bit beyond scope of what Cargo crates should be doing, so it can't be automated.

Point (2) could be automated for some well-known setups.
