### ISSUE TITLE
Add readme = "README.md" in cargo.toml to have the readme displayed on crates.io

### ISSUE THREAD

**Issue by pgimalac** [rust-lang/pkg-config-rs#110]
Not a big deal but I think it would seem cleaner on crates.io (https://crates.io/crates/pkg-config).

At the moment the only thing displayed is the description.

**Comment by sdroege** [comment]
Makes sense! Do you want to provide a PR for that?

**Comment by pgimalac** [comment]
As you wish ! It'll be done in a minute
