### ISSUE TITLE
Should we parse -isystem Cflags?

### ISSUE THREAD

**Issue by mfarrugi** [rust-lang/pkg-config-rs#114]
I have a library that is not being picked up correctly because it provides `-isystem` flags. Should https://github.com/rust-lang/pkg-config-rs/blob/master/src/lib.rs#L524 parse `-isystem` as well?

And `-iquote` for completeness?

**Comment by sdroege** [comment]
And `-idirafter`, I guess. Do you want to provide a PR for that?

**Comment by sdroege** [comment]
See https://github.com/rust-lang/pkg-config-rs/pull/115
