### ISSUE TITLE
customized pkg-config is incomplete?

### ISSUE THREAD

**Issue by igorbernstein** [rust-lang/pkg-config-rs#118]
Hi,

I'm fairly new to rust and cross compilation in general, so I apologize if I'm misunderstanding something. But it seems like https://github.com/rust-lang/pkg-config-rs/pull/86 is incomplete. It seems like it checks if `PKG_CONFIG_<triple>` is set to enable cross compilation, but doesn't actually use the wrapper script defined by that env var when constructing the command:
https://github.com/rust-lang/pkg-config-rs/blob/54325785816695df031cef3b26b6a9a203bbc01b/src/lib.rs#L396-L398

I believe that should be changed to:
```rust
            self.targetted_env_var("PKG_CONFIG")
```

**Comment by sdroege** [comment]
I think so too, thanks for checking! Do you want to provide a PR for this?
