### ISSUE TITLE
[Feature Request] Add configurable linking modifiers

### ISSUE THREAD

**Issue by estherlurie** [rust-lang/pkg-config-rs#136]
I am working on a project that links in static dependencies. Some of these dependencies have object files that break linking. Usually with C++ projects, these object files are never actually read, due to not using the `--whole-archive` modifier. Because of the rust compiler, however, there is a default linker setting of `+whole-archive` ([see here](https://github.com/rust-lang/rust/blob/4c5665583815a0f0f3e22516441efb43ea6dede2/compiler/rustc_codegen_ssa/src/back/link.rs#L2280-L2284)).

It would be useful to be able to add modifiers to this linker line:
https://github.com/rust-lang/pkg-config-rs/blob/4246c5a3ef4acba7eb3d37a47669e187df100711/src/lib.rs#L629-L630
The format is [specified in the Rustc book here](https://doc.rust-lang.org/rustc/command-line-arguments.html#-l-link-the-generated-crate-to-a-native-library). This way, I could explicity use `-l static:-whole-archive=mylib`.

**Comment by sdroege** [comment]
Wouldn't the more correct way to deal with this be to add these linker flags to the pkg-config file for these object files?

**Comment by estherlurie** [comment]
> Wouldn't the more correct way to deal with this be to add these linker flags to the pkg-config file for these object files?

That's one solution. However, the rustc default still is to add `+whole-archive` for every single library, not just the problematic ones. This can lead to a lot of unnecessary stuff getting linked in.

**Comment by estherlurie** [comment]
We've also discovered a related issue with rustc that would make this change unusable for now. [This section of the compiler](https://github.com/rust-lang/rust/blob/master/compiler/rustc_metadata/src/native_libs.rs#L422-L425) ends the link step if any two packages with the same names have modifiers; not if they have _different_ modifiers, but if they have any at all. So if we were able to add linking modifiers in this crate, it would error if any explicit dependencies share a dependency.

**Comment by sdroege** [comment]
How would you like this to work btw? Having API to specify per package, or even per library, linking modifiers? This seems like the wrong place for doing that to me. No other language I'm aware of needs this when consuming pkg-config files :)

**Comment by estherlurie** [comment]
So actually I think we can close this. It is not an issue with pkg-config but an issue with rustc where [`cargo test` defaults to `whole-archive`](https://github.com/rust-lang/rust/blob/4c5665583815a0f0f3e22516441efb43ea6dede2/compiler/rustc_codegen_ssa/src/back/link.rs#L2280-L2284). Thanks for chatting :)

**Comment by sdroege** [comment]
Thanks for the update!
