### ISSUE TITLE
Rustdoc docs are missing information about environment variables present in README

### ISSUE THREAD

**Issue by surban** [rust-lang/pkg-config-rs#156]
The section about "external configuration via target-scoped environment variables" is missing in the rustdoc-generated documentation. This is a bit unfortunate, since there is also no hint that information about cross-compiling is provided in the README.

**Comment by sdroege** [comment]
Indeed, thanks for noticing. Do you want to provide a PR that copies it over from the README.md?

**Comment by surban** [comment]
PR is linked.
