### ISSUE TITLE
If PKG_CONFIG is already overriden then default PKG_CONFIG_ALLOW_CROSS to yes

### ISSUE THREAD

**Issue by infinity0** [rust-lang/pkg-config-rs#41]
I've been trying to cross-compile cargo and although I've succeeded now, I ran into several cases where I had to set random environment variables for it to work. Here, `PKG_CONFIG_ALLOW_CROSS` seems a bit unnecessary, if `PKG_CONFIG` is already overriden then probably the user/builder knows what they're doing and there is no need to put artificial guards in that make the process Just Not Work.

**Comment by infinity0** [comment]
For reference, on Debian the cross-compiling `pkg-config` programs are called `$(host-triplet)-pkg-config` and they are just a simple wrapper around `pkg-config`.

This issue is more about the whole Rust ecosystem rather than this particular package, I'd rather not have to set 20 similar random environment variables in the future across various different crates.

**Comment by alexcrichton** [comment]
Seems reasonable to me!

**Comment by lightern** [comment]
Hi, maybe a stupid question, but how should I use PKG_CONFIG_ALLOW_CROSS variable? I've been trying to find the answer for this everywhere.
