### ISSUE TITLE
Don't use deny(warnings) in code

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/pkg-config-rs#55]
https://github.com/alexcrichton/pkg-config-rs/blob/175dd5596fb8bf1ebf66c4df0c8d013e568c6d58/src/lib.rs#L65

This basically breaks for everyone when lints are changed because people do run tests ;)

I think more appropriate to pass `-D warnings` or something like that to CI.

**Comment by sdroege** [comment]
This was removed a while ago

commit 5bb9d05f5eb7e43425a39a320a377c07cac5e2f2
Author: Alex Crichton <alex@alexcrichton.com>
Date:   Tue Apr 24 08:19:55 2018 -0700

    Remove deny(warnings)
