### ISSUE TITLE
please use PKG_CONFIG_KEEP_SYSTEM_CFLAGS and PKG_CONFIG_KEEP_SYSTEM_LIBS

### ISSUE THREAD

**Issue by kaniini** [rust-lang/pkg-config-rs#92]
The rust pkg_config crate parses the gcc cflags and link flag output of pkg-config to deduce semantic meaning behind certain flags.

There's nothing wrong with that per se, but pkgconf typically assumes that when invoked, it is generating output for use with the system C/C++ compiler.  Accordingly, it typically simplifies the output it generates for the convenience of humans using the tool by removing flags that gcc automatically implies (such as `-I/usr/include` for example).

This causes strange conflicts with the pkg_config crate naturally.  This can be fixed by telling pkgconf that you're not GCC, by adding two environment variables:

- `PKG_CONFIG_SYSTEM_INCLUDE_PATH=`
- `PKG_CONFIG_SYSTEM_LIBRARY_PATH=`

These paths should be either blank or paths that will automatically be implied by the toolchain.  In the case of rust-onig/rust-onig#119, the paths should be blank if the implied paths (e.g. `/usr/include`) will not be included in the `include_paths` property.

**Comment by sdroege** [comment]
Can you provide a PR for this? I don't have any system with pkgconf, so can't really test this.

**Comment by kaniini** [comment]
I am sure we can come up with something.  ping @ignatenkobrain (trust me, you don't want to see me writing rust, i don't know what i am doing in this language ;))
